baseURL = ""
languageCode = "zh-CN"
title = "首页导航"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
publishDir = "public"        # 站点静态文件保存目录
relativeURLs = true

[params]
author = "weekend-project"
description = "首页导航"
upload = ""
about = ""
repository = ""
enablePreLoad = true                                                    # 网站完全打开前预加载动画
textPreLoad = "首页导航"                                                 # 预加载的动画文字, 只有当enablePreLoad=true时生效
expandSidebar = false                                                   # 默认展开左侧边导航栏
logosPath = "assets/images/logos"                                       # 网站每个导航地址logo存放地址
defaultLogo = "assets/images/logos/default.webp"                        # logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功

[params.images]
favicon = "./assets/images/favicon.ico"
searchImageL = "./assets/images/bg.jpg"        # 搜索部分浅色背景图
searchImageD = "./assets/images/bg.jpg"        # 搜索部分深色背景图
logoExpandLight = "./assets/images/logo.png"
logoExpandDark = "./assets/images/logo.png"
logoCollapseLight = "./assets/images/logo.png"
logoCollapseDark = "./assets/images/logo.png"

[markup.goldmark.renderer]
unsafe = true

[params.footer]
version = "[开发版]"
copyright = 'Copyright © {year} Joseph Chris 修改版'
